#ifndef LIGHT_MOTION_SENSOR_LIGHT_SENSOR_H
#define LIGHT_MOTION_SENSOR_LIGHT_SENSOR_H

#define LIGHT_SENSOR_LUX_X100(v) ((unsigned int)v * 336 / 100)
#define VEML7700_LUX_TO_V(l) (l * 30)
#define LIGHT_SENSOR_HIGH_THRESHOLD_RAW VEML7700_LUX_TO_V(LIGHT_SENSOR_HIGH_THRESHOLD) // 3 lux / 0.0336
#define LIGHT_SENSOR_LOW_THRESHOLD_RAW  VEML7700_LUX_TO_V(LIGHT_SENSOR_LOW_THRESHOLD) // 1 lux / 0.0336

#endif
